Added autoupdater

diff --git a/bulwarkupdate b/bulwarkupdate
--- a/bulwarkupdate
+++ b/bulwarkupdate
@@ -1,9 +1,5 @@
 #!/bin/bash
 
-# Install curl before we do anything else
-echo "Installing curl and jq..."
-sudo apt-get install -y curl jq
-
 ASSETS=$(curl -s https://api.github.com/repos/bulwark-crypto/bulwark/releases/latest | jq '.assets')
 
 VPSTARBALLURL=$(echo "$ASSETS" | jq -r '.[] | select(.name|test("bulwark-node.*linux64")).browser_download_url')
@@ -14,29 +10,27 @@ SHNTARBALLNAME=$(echo "$SHNTARBALLURL" | cut -d "/" -f 9)
 LOCALVERSION=$(bulwark-cli --version | cut -d " " -f 6)
 REMOTEVERSION=$(curl -s https://api.github.com/repos/bulwark-crypto/bulwark/releases/latest | jq -r ".tag_name")
 
+USER="bulwark"
+USERHOME="/home/bulwark"
+
 if [[ "$LOCALVERSION" = "$REMOTEVERSION" ]]; then
   echo "No update necessary."
-  exit
+  exit 0
 fi
-
-clear
-echo "This script will update your wallet to version $BWKVERSION"
-read -rp "Press Ctrl-C to abort or any other key to continue. " -n1 -s
-clear
 
 if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root."
   exit 1
 fi
 
-USER="bulwark"
-USERHOME="/home/bulwark"
+USER=$(ps -o user= -p "$(pgrep bulwarkd)")
+USERHOME=$(eval echo "~$USER")
 
-echo "Shutting down wallet..."
+echo "Shutting down masternode..."
 if [ -e /etc/systemd/system/bulwarkd.service ]; then
   systemctl stop bulwarkd
 else
-  su -c "bulwark-cli stop" "bulwark"
+  su -c "bulwark-cli stop" "$USER"
 fi
 
 echo "Downloading and installing binaries..."
@@ -57,47 +51,13 @@ if [ -e /usr/bin/bulwark-cli ];then rm -rf /usr/bin/bulwark-cli; fi
 if [ -e /usr/bin/bulwark-tx ];then rm -rf /usr/bin/bulwark-tx; fi
 
 # Remove addnodes from bulwark.conf
-sed -i '/^addnode/d' "/home/bulwark/.bulwark/bulwark.conf"
+sed -i '/^addnode/d' "$USERHOME/.bulwark/bulwark.conf"
 
 # Add Fail2Ban memory hack if needed
 if ! grep -q "ulimit -s 256" /etc/default/fail2ban; then
   echo "ulimit -s 256" | sudo tee -a /etc/default/fail2ban
   systemctl restart fail2ban
 fi
-
-# Update bulwark-decrypt
-if [  -e /usr/local/bin/bulwark-decrypt ]; then sudo rm /usr/local/bin/bulwark-decrypt; fi
-
-sudo tee &> /dev/null /usr/local/bin/bulwark-decrypt << EOL
-#!/bin/bash
-
-# Stop writing to history
-set +o history
-
-# Confirm wallet is synced
-until sudo su -c "bulwark-cli mnsync status 2>/dev/null" bulwark | jq '.IsBlockchainSynced' | grep -q true; do
-  echo -ne "Current block: \$(sudo su -c "bulwark-cli getinfo" bulwark | jq '.blocks')\\r"
-  sleep 1
-done
-
-# Unlock wallet
-until sudo su -c "bulwark-cli getstakingstatus" bulwark | jq '.walletunlocked' | grep -q true; do
-
-  #ask for password and attempt it
-  read -e -s -p "Please enter a password to decrypt your staking wallet. Your password will not show as you type : " ENCRYPTIONKEY
-  sudo su -c "bulwark-cli walletpassphrase '\$ENCRYPTIONKEY' 0 true" bulwark
-done
-
-# Tell user all was successful
-echo "Wallet successfully unlocked!"
-echo " "
-sudo su -c "bulwark-cli getstakingstatus" bulwark
-
-# Restart history
-set -o history
-EOL
-
-sudo chmod a+x /usr/local/bin/bulwark-decrypt
 
 echo "Restarting Bulwark daemon..."
 if [ -e /etc/systemd/system/bulwarkd.service ]; then
@@ -126,54 +86,15 @@ EOL
 sudo systemctl enable bulwarkd
 sudo systemctl start bulwarkd
 
-until [ -n "$(bulwark-cli getconnectioncount 2>/dev/null)"  ]; do
-  sleep 1
-done
+sleep 20
 
-clear
-
-echo "Your wallet is syncing. Please wait for this process to finish."
-
-until sudo su -c "bulwark-cli mnsync status 2>/dev/null" bulwark | jq '.IsBlockchainSynced' | grep -q true; do
-  echo -ne "Current block: $(sudo su -c "bulwark-cli getinfo" bulwark | jq '.blocks')\\r"
-  sleep 1
-done
-
-clear
-
-echo "Installing Bulwark Autoupdater..."
 rm -f /usr/local/bin/bulwarkupdate
 curl -o /usr/local/bin/bulwarkupdate https://raw.githubusercontent.com/bulwark-crypto/Bulwark-MN-Install/master/bulwarkupdate
 chmod a+x /usr/local/bin/bulwarkupdate
 
-if [ ! -f /etc/systemd/system/bulwarkupdate.service ]; then
-cat > /etc/systemd/system/bulwarkupdate.service << EOL
-[Unit]
-Description=Bulwarks's Masternode Autoupdater
-After=network-online.target
-[Service]
-Type=oneshot
-User=root
-WorkingDirectory=${USERHOME}
-ExecStart=/usr/local/bin/bulwarkupdate
-EOL
+if ! systemctl status bulwarkd | grep -q "active (running)"; then
+  echo "ERROR: Failed to start bulwarkd. Please contact support."
+  exit
 fi
 
-if [ ! -f /etc/systemd/system/bulwarkupdate.timer ]; then
-cat > /etc/systemd/system/bulwarkupdate.timer << EOL
-[Unit]
-Description=Bulwarks's Masternode Autoupdater Timer
-
-[Timer]
-OnBootSec=1d
-OnUnitActiveSec=1d 
-
-[Install]
-WantedBy=timers.target
-EOL
-fi
-
-systemctl enable bulwarkupdate.timer
-systemctl start bulwarkupdate.timer
-
-echo "Bulwark is now up to date. Do not forget to unlock your wallet!"
+echo "Masternode is syncing. Masternode update completed."
